import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  BrandEntity,
  CategoryEntity,
  CollectionEntity,
  CollectionBannerEntity,
  ColorEntity,
  CurrencyEntity,
  GenderEntity,
  ModelEntity,
  OrderStateEntity,
  PaymentMethodEntity,
  ProductEntity,
  ProductImageEntity,
  ShippingMethodEntity,
  SizeEntity,
} from './entities';

import {
  BrandsService,
  CategoriesService,
  CollectionsService,
  CollectionBannersService,
  ColorsService,
  CurrenciesService,
  GendersService,
  ModelsService,
  OrderStatesService,
  PaymentMethodsService,
  ProductsService,
  ProductImagesService,
  RefsService,
  ShippingMethodsService,
  SizesService,
} from './services';

import {
  BrandsController,
  CategoriesController,
  CollectionsController,
  ColorsController,
  CurrenciesController,
  GendersController,
  ModelsController,
  OrderStatesController,
  PaymentMethodsController,
  ProductsController,
  RefsController,
  ShippingMethodsController,
  SizesController,
} from './controllers';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      BrandEntity,
      CategoryEntity,
      CollectionEntity,
      CollectionBannerEntity,
      ColorEntity,
      CurrencyEntity,
      GenderEntity,
      ModelEntity,
      OrderStateEntity,
      PaymentMethodEntity,
      ProductEntity,
      ProductImageEntity,
      ShippingMethodEntity,
      SizeEntity,
    ]),
  ],
  exports: [ProductsService, RefsService],
  controllers: [
    RefsController,
    BrandsController,
    CategoriesController,
    CollectionsController,
    ColorsController,
    CurrenciesController,
    GendersController,
    ModelsController,
    OrderStatesController,
    PaymentMethodsController,
    ProductsController,
    ShippingMethodsController,
    SizesController,
  ],
  providers: [
    RefsService,
    BrandsService,
    CategoriesService,
    CollectionsService,
    CollectionBannersService,
    ColorsService,
    CurrenciesService,
    GendersService,
    ModelsService,
    OrderStatesService,
    PaymentMethodsService,
    ProductsService,
    ProductImagesService,
    ShippingMethodsService,
    SizesService,
  ],
})
export class RefsModule {}
