SET NAMES 'utf8mb4';

INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', null, 12, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', null, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', null, 7, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Комп\'ютер і офіс', 'Computer & Office', null, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Побутова електроніка', 'Consumer Electronics', null, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', null, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', null, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Товари для дітей', 'Goods for kids', null, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 1', 'Categories 1', 1, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 2', 'Categories 2', 1, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 3', 'Categories 3', 1, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 9, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 9, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 9, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 9, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 9, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 10, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 10, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 10, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 10, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 10, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 11, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 11, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 11, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 11, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 11, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 1', 'Categories 1', 3, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 2', 'Categories 2', 3, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 3', 'Categories 3', 3, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 4', 'Categories 4', 3, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 27, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 27, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 27, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 27, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 27, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 28, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 28, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 28, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 28, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 28, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 29, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 29, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 29, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 29, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 29, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 30, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 30, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 30, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 30, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 30, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 1', 'Categories 1', 6, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 2', 'Categories 2', 6, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 3', 'Categories 3', 6, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 4', 'Categories 4', 6, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 5', 'Categories 5', 6, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 6', 'Categories 6', 6, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 51, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 51, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 51, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 51, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 51, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 52, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 52, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 52, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 52, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 52, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 53, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 53, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 53, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 53, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 53, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 54, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 54, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 54, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 54, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 54, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 55, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 55, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 55, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 55, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 55, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 56, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 56, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 56, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 56, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 56, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 1', 'Categories 1', 2, null, 'bc07188dd8f7f7c.jpg', 'Жіноче', 'Women’s');
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 2', 'Categories 2', 2, null, '6160188dd919675.jpg', 'Чоловіче', 'Men’s');
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 3', 'Categories 3', 2, null, 'a4ac188dd928522.jpg', 'Аксесуари', 'Accessories');
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Категорії 4', 'Categories 4', 2, null, '0f53188dd935efe.jpg', 'Сумки', 'Bags');
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 87, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 87, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 87, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 87, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 87, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 88, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 88, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 88, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 88, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 88, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 89, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 89, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 89, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 89, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 89, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Жіноча одежа', 'Women’s Clothing', 90, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Чоловіче вбрання', 'Men’s Clothing', 90, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Телефони та Аксесуари', 'Phones & Accessories', 90, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Ювелірні вироби та годинники', 'Jewelry & Watches', 90, null, null, null, null);
INSERT INTO e_shop.categories (name_uk, name_en, parent_id, collection_id, banner_image, banner_name_uk, banner_name_en) VALUES ('Сумки та взуття', 'Bags & Shoes', 90, null, null, null, null);
