call docker-exec profiles.sql
call docker-exec brands.sql
call docker-exec collections.sql
call docker-exec collection_banners.sql
call docker-exec categories.sql
call docker-exec colors.sql
call docker-exec currencies.sql
call docker-exec genders.sql
call docker-exec models.sql
call docker-exec order_states.sql
call docker-exec payment_methods.sql
call docker-exec shipping_methods.sql
call docker-exec sizes.sql
call docker-exec products.sql
call docker-exec product_images.sql
call docker-exec reviews.sql